/*
 * This file is generated by jOOQ.
 */
package edu.uci.ics.texera.dataflow.resource.dictionaryJooq;


import edu.uci.ics.texera.dataflow.resource.dictionaryJooq.tables.Dictionary;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index DICTIONARY_NAME_INDEX = Indexes0.DICTIONARY_NAME_INDEX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index DICTIONARY_NAME_INDEX = Internal.createIndex("DICTIONARY_NAME_INDEX", Dictionary.DICTIONARY, new OrderField[] { Dictionary.DICTIONARY.NAME }, false);
    }
}
