/*
 * This file is generated by jOOQ.
 */
package edu.uci.ics.texera.dataflow.resource.dictionaryJooq;


import edu.uci.ics.texera.dataflow.resource.dictionaryJooq.tables.Dictionary;
import edu.uci.ics.texera.dataflow.resource.dictionaryJooq.tables.records.DictionaryRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<DictionaryRecord, Integer> IDENTITY_DICTIONARY = Identities0.IDENTITY_DICTIONARY;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DictionaryRecord> PK_DICTIONARY = UniqueKeys0.PK_DICTIONARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<DictionaryRecord, Integer> IDENTITY_DICTIONARY = Internal.createIdentity(Dictionary.DICTIONARY, Dictionary.DICTIONARY.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<DictionaryRecord> PK_DICTIONARY = Internal.createUniqueKey(Dictionary.DICTIONARY, "pk_DICTIONARY", Dictionary.DICTIONARY.ID);
    }
}
