/*
 * This file is generated by jOOQ.
 */
package edu.uci.ics.texera.dataflow.resource.dictionaryJooq;


import edu.uci.ics.texera.dataflow.resource.dictionaryJooq.tables.Dictionary;
import edu.uci.ics.texera.dataflow.resource.dictionaryJooq.tables.SqliteSequence;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>DICTIONARY</code>.
     */
    public static final Dictionary DICTIONARY = edu.uci.ics.texera.dataflow.resource.dictionaryJooq.tables.Dictionary.DICTIONARY;

    /**
     * The table <code>sqlite_sequence</code>.
     */
    public static final SqliteSequence SQLITE_SEQUENCE = edu.uci.ics.texera.dataflow.resource.dictionaryJooq.tables.SqliteSequence.SQLITE_SEQUENCE;
}
