/*
 * This file is generated by jOOQ.
 */
package edu.uci.ics.texera.web.resource.metadata;


import edu.uci.ics.texera.web.resource.metadata.tables.Dictionary;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>metadata</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index DICTIONARY_PRIMARY = Indexes0.DICTIONARY_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index DICTIONARY_PRIMARY = Internal.createIndex("PRIMARY", Dictionary.DICTIONARY, new OrderField[] { Dictionary.DICTIONARY.ID }, true);
    }
}
