/*
 * This file is generated by jOOQ.
 */
package edu.uci.ics.texera.web.resource.metadata;


import edu.uci.ics.texera.web.resource.metadata.tables.Dictionary;
import edu.uci.ics.texera.web.resource.metadata.tables.records.DictionaryRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>metadata</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DictionaryRecord> KEY_DICTIONARY_PRIMARY = UniqueKeys0.KEY_DICTIONARY_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<DictionaryRecord> KEY_DICTIONARY_PRIMARY = Internal.createUniqueKey(Dictionary.DICTIONARY, "KEY_Dictionary_PRIMARY", Dictionary.DICTIONARY.ID);
    }
}
