/*
 * This file is generated by jOOQ.
 */
package edu.uci.ics.texera.web.resource.metadata;


import edu.uci.ics.texera.web.resource.metadata.tables.Dictionary;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Metadata extends SchemaImpl {

    private static final long serialVersionUID = -700703788;

    /**
     * The reference instance of <code>metadata</code>
     */
    public static final Metadata METADATA = new Metadata();

    /**
     * The table <code>metadata.Dictionary</code>.
     */
    public final Dictionary DICTIONARY = edu.uci.ics.texera.web.resource.metadata.tables.Dictionary.DICTIONARY;

    /**
     * No further instances allowed
     */
    private Metadata() {
        super("metadata", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Dictionary.DICTIONARY);
    }
}
