/*
 * This file is generated by jOOQ.
 */
package edu.uci.ics.texera.web.resource.metadata;


import edu.uci.ics.texera.web.resource.metadata.tables.Dictionary;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in metadata
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>metadata.Dictionary</code>.
     */
    public static final Dictionary DICTIONARY = edu.uci.ics.texera.web.resource.metadata.tables.Dictionary.DICTIONARY;
}
